#自作エラー用
class MyError(Exception):
    pass